# This is a sample build configuration for PHP.
# Check our guides at https://confluence.atlassian.com/x/e8YWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:14.17.3

pipelines:
  branches:
    master:
      - step:
          name: Deploy to staging server
          deployment: staging
          script:
            - pipe: atlassian/ssh-run:0.2.2
              variables:
                SSH_USER: 'radoan'
                SERVER: 'adf.pranjolerp.com'
                MODE: 'script'
                COMMAND: './execute.sh'

